//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASN_FILES
    {
        public string FILE_NAME { get; set; }
        public string FILE_NAME_SAVED { get; set; }
        public string VENDOR_ID { get; set; }
        public Nullable<System.DateTime> DATE_RECEIVED { get; set; }
    }
}
