//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_INVENTORY
    {
        public int C_RID_ { get; set; }
        public string TRANTYPE { get; set; }
        public string SUBTYPE { get; set; }
        public System.DateTime TRANSACTION_TIME { get; set; }
        public string USER_ID { get; set; }
        public Nullable<int> INV_RID { get; set; }
        public Nullable<int> INV_RID_OLD { get; set; }
        public string PRODUCT_ID { get; set; }
        public string PRODUCT_ID_OLD { get; set; }
        public string FROM_INV_BASELABEL { get; set; }
        public string INV_BASELABEL_OLD { get; set; }
        public string INV_TRACE { get; set; }
        public string INV_TRACE_OLD { get; set; }
        public Nullable<float> INV_QTY { get; set; }
        public Nullable<float> INV_QTY_OLD { get; set; }
        public string UOM { get; set; }
        public string UOM_OLD { get; set; }
        public string OWNER_ID { get; set; }
        public string OWNER_ID_OLD { get; set; }
        public string SITE_ID { get; set; }
        public string SITE_ID_OLD { get; set; }
        public string LOCATION_ID { get; set; }
        public string LOCATION_ID_OLD { get; set; }
        public string QC_CATEGORY { get; set; }
        public string QC_CATEGORY_OLD { get; set; }
        public Nullable<System.DateTime> EXPORTTIME_SYS1 { get; set; }
        public Nullable<int> EXPORTLOADNUM_SYS1 { get; set; }
        public Nullable<System.DateTime> EXPORTTIME_SYS2 { get; set; }
        public Nullable<int> EXPORTLOADNUM_SYS2 { get; set; }
        public Nullable<System.DateTime> EXPORTTIME_SYS3 { get; set; }
        public Nullable<int> EXPORTLOADNUM_SYS3 { get; set; }
        public string TRAILERRAILBOATLABEL { get; set; }
        public string CONTAINERLABEL { get; set; }
        public string PALLETTOTELABEL { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
        public string CARRIER_ID { get; set; }
    }
}
