//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_PICK_TICKET
    {
        public int APT_ID { get; set; }
        public string SHIPMENT_ID { get; set; }
        public string TRANSACTION_TYPE { get; set; }
        public string USER_ID { get; set; }
        public string ORIGINAL_P_TIME { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
    }
}
