//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrier_Cut_Off
    {
        public string Carrier_Name { get; set; }
        public int Cut_Off_Time { get; set; }
        public string Carrier_ID { get; set; }
        public int ID { get; set; }
    }
}
