//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cashier_Notes
    {
        public string Transaction_rid { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Last_Updated { get; set; }
    }
}
