//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cashier_Transactions
    {
        public string C_rid_ { get; set; }
        public string userid { get; set; }
        public string shipment_id { get; set; }
        public decimal transaction_amount { get; set; }
        public string transaction_type { get; set; }
        public System.DateTime C_last_updated_ { get; set; }
        public byte[] signatureImg { get; set; }
        public string printedName { get; set; }
        public string Guid { get; set; }
        public string Check_Number { get; set; }
    }
}
