//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComparePM2UOM
    {
        public string Product_ID { get; set; }
        public string HasCaseUOM { get; set; }
        public string HasEachUOM { get; set; }
        public string MatchCaseQty { get; set; }
    }
}
