//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public string CUSTOMER_ID { get; set; }
        public string BILL_TO_ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS_1 { get; set; }
        public string ADDRESS_2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string PHONE { get; set; }
        public bool SPECIAL_PICKING { get; set; }
        public bool SPECIAL_PALLETS { get; set; }
        public bool INBOUND_EDI { get; set; }
        public bool OUTBOUND_EDI { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
        public string EMAIL_ADDRESS { get; set; }
    }
}
