//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYCLE_COUNT_REQUESTS
    {
        public int C_RID_ { get; set; }
        public string LOCATION_ID { get; set; }
        public string ZONE { get; set; }
        public string AISLE { get; set; }
        public string VLEVEL { get; set; }
        public string PRODUCT_ID { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string USER_ID { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
    }
}
