//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORM_DETAIL
    {
        public string FORM { get; set; }
        public string FIELD { get; set; }
        public string FIELD_TYPE { get; set; }
        public Nullable<int> SIZE { get; set; }
        public Nullable<int> LOOKUP { get; set; }
        public string LOOKUP_TABLE { get; set; }
        public Nullable<int> SEARCH { get; set; }
        public Nullable<int> RESULTS { get; set; }
        public Nullable<int> RESULTS_COLUMN { get; set; }
        public Nullable<int> SEARCH_ROW { get; set; }
        public Nullable<int> COLUMN_NUMBER { get; set; }
        public Nullable<int> MAX_SIZE { get; set; }
        public string FIELD_DESCRIPTION { get; set; }
        public Nullable<int> VALIDATE { get; set; }
        public string VALIDATE_TABLE { get; set; }
        public string VALIDATE_FIELD { get; set; }
        public string FORM_TYPE { get; set; }
    }
}
