//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOST_INVENTORY_STATE
    {
        public string PRODUCT_ID { get; set; }
        public string STATUS { get; set; }
        public float HOST_QUANTITY { get; set; }
        public float WMS_QUANTITY { get; set; }
        public bool NO_HOST_INV { get; set; }
        public bool NO_WMS_INV { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
    }
}
