//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORT_DEFS
    {
        public string SOURCE_TABLE { get; set; }
        public string SOURCE_FIELD { get; set; }
        public string TARGET_TABLE { get; set; }
        public string TARGET_FIELD { get; set; }
        public string PROCESSING_DESCRIPTION { get; set; }
        public string TARGET_DESCRIPTION { get; set; }
        public string DATATYPE { get; set; }
        public Nullable<short> LENGTH { get; set; }
        public bool INPUT_KEY { get; set; }
        public bool OUTPUT_KEY { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
        public Nullable<short> FLATFILE_SEQ { get; set; }
    }
}
