//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class INBOUND_SHIPMENT_DETAIL
    {
        public string SHIPMENT_ID { get; set; }
        public string ORDER_NUMBER { get; set; }
        public short ORDER_LINE { get; set; }
        public string CUSTOMER_TRACKING_NUMBER { get; set; }
        public string PRODUCT_ID { get; set; }
        public Nullable<int> CONTROL_CONTAINER_COUNT { get; set; }
        public Nullable<float> CONTROL_QUANTITY { get; set; }
        public string CONTROL_UOM { get; set; }
        public Nullable<int> ACTUAL_CONTAINER_COUNT { get; set; }
        public Nullable<float> ACTUAL_QUANTITY { get; set; }
        public string ACTUAL_UOM { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
        public Nullable<float> UNLOADED_CONTAINER_COUNT { get; set; }
        public Nullable<float> UNLOADED_QUANTITY { get; set; }
        public string UNLOADED_UOM { get; set; }
        public string LABELPRINT_STATUS { get; set; }
        public Nullable<System.DateTime> ExportTime_Sys1 { get; set; }
    }
}
