//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pickers_Move_Queue
    {
        public int C_RID_ { get; set; }
        public string User_Id { get; set; }
        public string Location_id { get; set; }
        public string Shipment_id { get; set; }
        public string Case_number { get; set; }
        public string Box_Size { get; set; }
        public string Customer_id { get; set; }
        public string Purchase_Order { get; set; }
        public System.DateTime C_Last_Updated_ { get; set; }
        public Nullable<bool> Flag { get; set; }
        public string Status { get; set; }
        public System.DateTime C_Date_Created_ { get; set; }
    }
}
