//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickUp_Rack_Locations
    {
        public string LOCATION_ID { get; set; }
        public string LOCATION_GROUP { get; set; }
        public string EIS_LOCATION { get; set; }
        public int PICK_SEQUENCE { get; set; }
        public string AISLE { get; set; }
        public string SLOT { get; set; }
        public string VLEVEL { get; set; }
        public string BIN { get; set; }
        public string STATUS { get; set; }
        public string SITE_ID { get; set; }
        public string PICKING_ZONE { get; set; }
        public string PUTAWAY_ZONE { get; set; }
        public bool ALLOWPIECEPICKING { get; set; }
        public string TYPE { get; set; }
        public string USAGE { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
        public Nullable<int> PUTAWAY_SEQUENCE { get; set; }
        public string REVERSE_SLOT { get; set; }
    }
}
