//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUTAWAY_RULES_DETAIL
    {
        public string RULE_ID { get; set; }
        public short SEQUENCE { get; set; }
        public string CONSOLIDATION_RULE { get; set; }
        public string USE_ZONE_OR_GROUP { get; set; }
        public string PRODUCT_ZONE { get; set; }
        public string LOCATION_ATTRIBUTE { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
        public string PROXIMITY_BASE { get; set; }
    }
}
