//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETURNS_DETAIL
    {
        public string RETURN_ID { get; set; }
        public int ORDER_LINE { get; set; }
        public string PRODUCT_ID { get; set; }
        public string STATUS { get; set; }
        public Nullable<float> RETURNED_QUANTITY { get; set; }
        public string COMMENTS_1 { get; set; }
        public string COMMENTS_2 { get; set; }
        public Nullable<System.DateTime> DATA1DATE { get; set; }
        public Nullable<float> DATA1NUM { get; set; }
        public string DATA1STR { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
    }
}
