//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScancodeCartonAcceptQueue
    {
        public string Carton { get; set; }
        public string TrackingNum { get; set; }
        public string ActWeight { get; set; }
        public string ShipLine { get; set; }
        public string PayFlag { get; set; }
        public string ActFreight { get; set; }
        public string ManiPrinter { get; set; }
        public System.DateTime Transaction_Time { get; set; }
        public string Status { get; set; }
    }
}
