//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBSTITUTION_RULES
    {
        public string RULE_ID { get; set; }
        public string SUBST_PRODUCT_ID { get; set; }
        public Nullable<float> QTY_PER_SOURCE_QTY { get; set; }
        public string SOURCE_UOM { get; set; }
        public string SUBST_UOM { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
    }
}
