//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_Users
    {
        public string User_ID { get; set; }
        public string Password { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<bool> QC_Required { get; set; }
        public Nullable<int> Shift_ID { get; set; }
        public Nullable<System.DateTime> Last_Log_In { get; set; }
        public Nullable<bool> QCRole { get; set; }
        public Nullable<bool> PickerRole { get; set; }
        public Nullable<bool> DriverRole { get; set; }
        public Nullable<bool> ManagerRole { get; set; }
        public Nullable<bool> DeveloperRole { get; set; }
    }
}
