//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_INBOUND
    {
        public int C_RID_ { get; set; }
        public string TRANTYPE { get; set; }
        public string SUBTYPE { get; set; }
        public System.DateTime TRANSACTION_TIME { get; set; }
        public Nullable<System.DateTime> APPOINTMENT_TIME { get; set; }
        public Nullable<System.DateTime> APPOINTMENT_TIME_OLD { get; set; }
        public string DOOR_ID { get; set; }
        public string DOOR_ID_OLD { get; set; }
        public Nullable<System.DateTime> MADE_TIME { get; set; }
        public Nullable<System.DateTime> MADE_TIME_OLD { get; set; }
        public Nullable<int> DURATION { get; set; }
        public Nullable<int> DURATION_OLD { get; set; }
        public string SENDER { get; set; }
        public string SENDER_OLD { get; set; }
        public string CARRIER_ID { get; set; }
        public string CARRIER_ID_OLD { get; set; }
        public string SHIPMENT_ID { get; set; }
        public string SHIPMENT_ID_OLD { get; set; }
        public Nullable<System.DateTime> ARRIVAL_TIME { get; set; }
        public Nullable<System.DateTime> PICK_ASSIGNED_TIME { get; set; }
        public Nullable<System.DateTime> PICK_START_TIME { get; set; }
        public Nullable<System.DateTime> PICK_COMPLETE_TIME { get; set; }
        public Nullable<System.DateTime> DEPARTURE_TIME { get; set; }
        public Nullable<System.DateTime> EXPORTTIME_SYS1 { get; set; }
        public Nullable<int> EXPORTLOADNUM_SYS1 { get; set; }
        public Nullable<System.DateTime> EXPORTTIME_SYS2 { get; set; }
        public Nullable<int> EXPORTLOADNUM_SYS2 { get; set; }
        public Nullable<System.DateTime> EXPORTTIME_SYS3 { get; set; }
        public Nullable<int> EXPORTLOADNUM_SYS3 { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
    }
}
