//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOST_ORDER_DETAIL
    {
        public string EIS_ORDER_ID { get; set; }
        public short EIS_ORDER_LINE { get; set; }
        public string TYPE { get; set; }
        public string PRODUCT_ID { get; set; }
        public string QC_CATEGORY { get; set; }
        public Nullable<float> ORDERED_UNITS { get; set; }
        public string UOM { get; set; }
        public Nullable<System.DateTime> SCHEDULED_DATE { get; set; }
        public string NOTES { get; set; }
        public Nullable<float> EIS_ORDLINE_PRICE { get; set; }
        public Nullable<decimal> EIS_UNIT_PRICE { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
    }
}
