//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int C_RID_ { get; set; }
        public string CASELABEL { get; set; }
        public string PALLETTOTELABEL { get; set; }
        public string CONTAINERLABEL { get; set; }
        public string TRAILERRAILBOATLABEL { get; set; }
        public string PRODUCT_ID { get; set; }
        public string TRACE_ID { get; set; }
        public string OWNER_ID { get; set; }
        public string LOCATION_ID { get; set; }
        public Nullable<float> QUANTITY { get; set; }
        public string QC_CATEGORY { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATE { get; set; }
        public Nullable<System.DateTime> MFG_DATETIME { get; set; }
        public Nullable<System.DateTime> RECEIPT_DATE { get; set; }
        public bool RESERVED { get; set; }
        public bool HOLD { get; set; }
        public string RESERVATION_TYPE { get; set; }
        public string SHIPMENT_ID { get; set; }
        public string ORDER_NUMBER { get; set; }
        public Nullable<short> ORDER_LINE { get; set; }
        public Nullable<System.DateTime> DATA1DATE { get; set; }
        public Nullable<float> DATA1NUM { get; set; }
        public string DATA1STR { get; set; }
        public Nullable<System.DateTime> DATA2DATE { get; set; }
        public Nullable<float> DATA2NUM { get; set; }
        public string DATA2STR { get; set; }
        public Nullable<System.DateTime> DATA3DATE { get; set; }
        public Nullable<float> DATA3NUM { get; set; }
        public string DATA3STR { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
    }
}
