//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADJUSTMENT_CODES
    {
        public string ADJUSTMENT_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public bool GL_ACCOUNT_REQUIRED { get; set; }
        public bool AMOUNT_REQUIRED { get; set; }
        public bool WMS_ONLY { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
    }
}
