//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFX_USERS
    {
        public string USER_ID { get; set; }
        public string NAME { get; set; }
        public string PASSWORD { get; set; }
        public bool LOG_ACCESS { get; set; }
        public bool DENY_ACCESS { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
        public bool QC_REQUIRED { get; set; }
        public Nullable<System.DateTime> QC_EXPIRE_DATE { get; set; }
    }
}
