//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_ASN
    {
        public int RID { get; set; }
        public string TRANTYPE { get; set; }
        public string SUBTYPE { get; set; }
        public Nullable<System.DateTime> TRANTIME { get; set; }
        public string FILE_NAME { get; set; }
        public string ALT_FILE_NAME { get; set; }
        public string SHIPMENT_ID { get; set; }
        public string BOL_NUMBER { get; set; }
        public string SHIP_TO_ACCOUNT { get; set; }
        public string PRODUCT_ID { get; set; }
        public string GTIN { get; set; }
        public string VENDOR_ID { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<System.DateTime> EXPORTTIME1 { get; set; }
        public Nullable<System.DateTime> EXPORTTIME2 { get; set; }
        public Nullable<System.DateTime> EXPORTTIME3 { get; set; }
        public string LAST_USER { get; set; }
        public string LAST_MODULE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
    }
}
