//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compare_IBR_Receipts
    {
        public string Inv_Trace { get; set; }
        public string Product_ID { get; set; }
        public string Short_Description { get; set; }
        public Nullable<double> RecvQty { get; set; }
        public int IBRQty { get; set; }
    }
}
