//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERRORS_RUNTIME
    {
        public int C_RID_ { get; set; }
        public System.DateTime ERRORTIME { get; set; }
        public string USERID { get; set; }
        public string MODULE { get; set; }
        public string FUNCTION { get; set; }
        public string ERRORTYPE { get; set; }
        public Nullable<int> ERRORNUMBER { get; set; }
        public string ERRORMESSAGE { get; set; }
        public string ERRORDATA { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
    }
}
