//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORM
    {
        public string FORM1 { get; set; }
        public string FORM_TYPE { get; set; }
        public Nullable<int> EDIT_WIDTH { get; set; }
        public Nullable<int> EDIT_LENGTH { get; set; }
    }
}
