//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FREIGHT_LANES
    {
        public string CARRIER_ID { get; set; }
        public string TYPE { get; set; }
        public string SHIP_MODE { get; set; }
        public string ZIP3_FROM { get; set; }
        public string ZIP3_THRU { get; set; }
        public Nullable<short> DAY_DELAY { get; set; }
        public bool ALLOW_EXCEPTIONS { get; set; }
        public System.DateTime EFFECTIVE_FROM_DATE { get; set; }
        public System.DateTime EFFECTIVE_THRU_DATE { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
        public string FullZip_From { get; set; }
        public string FullZip_Thru { get; set; }
    }
}
