//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOST_INVENTORY_EFFECT
    {
        public int C_RID_ { get; set; }
        public string TRANTYPE { get; set; }
        public string SUBTYPE { get; set; }
        public Nullable<System.DateTime> TRANSACTION_TIME { get; set; }
        public string PRODUCT_ID { get; set; }
        public string INV_ID { get; set; }
        public string FROM_SITE_ID { get; set; }
        public string FROM_HOSTLOCATION { get; set; }
        public string FROM_QC_CATEGORY { get; set; }
        public string FROM_QC_REASON { get; set; }
        public string TO_SITE_ID { get; set; }
        public string TO_HOSTLOCATION { get; set; }
        public string TO_QC_CATEGORY { get; set; }
        public string TO_QC_REASON { get; set; }
        public string DATA1STR { get; set; }
        public Nullable<float> DATA1NUM { get; set; }
        public Nullable<System.DateTime> DATA1DATE { get; set; }
        public string DATA2STR { get; set; }
        public Nullable<float> DATA2NUM { get; set; }
        public Nullable<System.DateTime> DATA2DATE { get; set; }
        public string DATA3STR { get; set; }
        public Nullable<float> DATA3NUM { get; set; }
        public Nullable<System.DateTime> DATA3DATE { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
    }
}
