//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOST_PRODMAST
    {
        public string EIS_PRODUCT_ID { get; set; }
        public string VENDOR_ID { get; set; }
        public string SHORT_DESCRIPTION { get; set; }
        public string BASE_UOM { get; set; }
        public float BASE_UOM_PER_CSN { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public Nullable<float> CASELEVEL_WEIGHT { get; set; }
        public Nullable<float> EIS_QTY_ONORDER { get; set; }
        public Nullable<float> EIS_QTY_ONHAND { get; set; }
        public Nullable<float> EIS_MILL_PURCHASE_PRICE { get; set; }
        public Nullable<float> EIS_AVG_UNIT_COST { get; set; }
        public Nullable<float> EIS_PACKAGE_QTY { get; set; }
        public string EIS_SIZE { get; set; }
        public string EIS_MILL_STYLE_NUMBER { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
    }
}
