//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORT_ENGINE_DEFS
    {
        public string IMPORT { get; set; }
        public string SOURCE_TABLE { get; set; }
        public string SOURCE_FIELD { get; set; }
        public Nullable<int> SOURCE_KEY { get; set; }
        public string TARGET_TABLE { get; set; }
        public string TARGET_FIELD { get; set; }
        public Nullable<int> TARGET_KEY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
        public string LAST_USER { get; set; }
        public string LAST_MODULE { get; set; }
    }
}
