//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class INBOUND_CSN
    {
        public int C_RID_ { get; set; }
        public string SHIPMENT_ID { get; set; }
        public string ORDER_NUMBER { get; set; }
        public string PRODUCT_ID { get; set; }
        public string CASELABEL { get; set; }
        public string PALLETTOTELABEL { get; set; }
        public string RECEIVING_STATUS { get; set; }
        public string QC_CATEGORY { get; set; }
        public string QC_REASON { get; set; }
        public string QC_DEFECT { get; set; }
        public string LOT_NUMBER { get; set; }
        public string MFG_VERSION_ID { get; set; }
        public string MFG_LINE_ID { get; set; }
        public string MFG_SHIFT_ID { get; set; }
        public Nullable<System.DateTime> MFG_DATE { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATE { get; set; }
        public Nullable<System.DateTime> SHIPBY_DATE { get; set; }
        public float QUANTITY { get; set; }
        public string UOM { get; set; }
        public string LABELPRINT_STATUS { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
    }
}
