//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public string App_Id { get; set; }
        public short Option_Number { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
    }
}
