//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WMSEntities : DbContext
    {
        public WMSEntities()
            : base("name=WMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADJUSTMENT_CODES> ADJUSTMENT_CODES { get; set; }
        public virtual DbSet<AFX_BROWSER_APPS> AFX_BROWSER_APPS { get; set; }
        public virtual DbSet<AFX_BROWSER_LINKS> AFX_BROWSER_LINKS { get; set; }
        public virtual DbSet<AFX_BROWSER_MENU> AFX_BROWSER_MENU { get; set; }
        public virtual DbSet<AFX_CONSOLE_APPS> AFX_CONSOLE_APPS { get; set; }
        public virtual DbSet<AFX_CONSOLE_LINKS> AFX_CONSOLE_LINKS { get; set; }
        public virtual DbSet<AFX_CONSOLE_MENU> AFX_CONSOLE_MENU { get; set; }
        public virtual DbSet<AFX_GROUPS> AFX_GROUPS { get; set; }
        public virtual DbSet<AFX_PREFERENCES> AFX_PREFERENCES { get; set; }
        public virtual DbSet<AFX_RIGHTS> AFX_RIGHTS { get; set; }
        public virtual DbSet<AFX_SYSINFO> AFX_SYSINFO { get; set; }
        public virtual DbSet<AFX_SYSTABLEMAP> AFX_SYSTABLEMAP { get; set; }
        public virtual DbSet<AFX_SYSTEMS> AFX_SYSTEMS { get; set; }
        public virtual DbSet<AFX_TABLES> AFX_TABLES { get; set; }
        public virtual DbSet<AFX_USERS> AFX_USERS { get; set; }
        public virtual DbSet<AUDIT_INBOUND> AUDIT_INBOUND { get; set; }
        public virtual DbSet<AUDIT_INBOUND_DETAIL> AUDIT_INBOUND_DETAIL { get; set; }
        public virtual DbSet<AUDIT_INVENTORY> AUDIT_INVENTORY { get; set; }
        public virtual DbSet<AUDIT_INVENTORY_DETAIL> AUDIT_INVENTORY_DETAIL { get; set; }
        public virtual DbSet<Audit_Manifest> Audit_Manifest { get; set; }
        public virtual DbSet<AUDIT_OUTBOUND> AUDIT_OUTBOUND { get; set; }
        public virtual DbSet<AUDIT_OUTBOUND_DETAIL> AUDIT_OUTBOUND_DETAIL { get; set; }
        public virtual DbSet<AUDIT_PICK_TICKET> AUDIT_PICK_TICKET { get; set; }
        public virtual DbSet<BOL_CLASS> BOL_CLASS { get; set; }
        public virtual DbSet<CARRIER> CARRIERS { get; set; }
        public virtual DbSet<CARTON_MASTER> CARTON_MASTER { get; set; }
        public virtual DbSet<Cashier_Notes> Cashier_Notes { get; set; }
        public virtual DbSet<Cashier_Transactions> Cashier_Transactions { get; set; }
        public virtual DbSet<CONSOLIDATION_RULES> CONSOLIDATION_RULES { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERS { get; set; }
        public virtual DbSet<CYCLE_COUNT_RESULTS> CYCLE_COUNT_RESULTS { get; set; }
        public virtual DbSet<DOCK_ACTIVITY> DOCK_ACTIVITY { get; set; }
        public virtual DbSet<DOOR> DOORS { get; set; }
        public virtual DbSet<EMAIL_ALIAS> EMAIL_ALIAS { get; set; }
        public virtual DbSet<EMAIL_GROUPS> EMAIL_GROUPS { get; set; }
        public virtual DbSet<EMAIL_QUEUE> EMAIL_QUEUE { get; set; }
        public virtual DbSet<ERRORS_RUNTIME> ERRORS_RUNTIME { get; set; }
        public virtual DbSet<ERRORS_USAGE> ERRORS_USAGE { get; set; }
        public virtual DbSet<FREIGHT_LANES> FREIGHT_LANES { get; set; }
        public virtual DbSet<GTIN_XREF> GTIN_XREF { get; set; }
        public virtual DbSet<GTIN_XREF_MASTER> GTIN_XREF_MASTER { get; set; }
        public virtual DbSet<HOST_INVENTORY_EFFECT> HOST_INVENTORY_EFFECT { get; set; }
        public virtual DbSet<HOST_INVENTORY_STATE> HOST_INVENTORY_STATE { get; set; }
        public virtual DbSet<HOST_ORDER_DETAIL> HOST_ORDER_DETAIL { get; set; }
        public virtual DbSet<HOST_ORDERS> HOST_ORDERS { get; set; }
        public virtual DbSet<HOST_PRODMAST> HOST_PRODMAST { get; set; }
        public virtual DbSet<INBOUND_CSN> INBOUND_CSN { get; set; }
        public virtual DbSet<INBOUND_MOVES> INBOUND_MOVES { get; set; }
        public virtual DbSet<INBOUND_SERIAL> INBOUND_SERIAL { get; set; }
        public virtual DbSet<INBOUND_SHIPMENT_DETAIL> INBOUND_SHIPMENT_DETAIL { get; set; }
        public virtual DbSet<INBOUND_SHIPMENTS> INBOUND_SHIPMENTS { get; set; }
        public virtual DbSet<INHOUSE_MOVES> INHOUSE_MOVES { get; set; }
        public virtual DbSet<INVENTORY> INVENTORies { get; set; }
        public virtual DbSet<INVENTORY_ALLOCATION> INVENTORY_ALLOCATION { get; set; }
        public virtual DbSet<INVENTORY_SERIAL> INVENTORY_SERIAL { get; set; }
        public virtual DbSet<LOCATION_CAPACITY> LOCATION_CAPACITY { get; set; }
        public virtual DbSet<LOCATION> LOCATIONS { get; set; }
        public virtual DbSet<LOOKUP_VALUES> LOOKUP_VALUES { get; set; }
        public virtual DbSet<MOVE_QUEUE> MOVE_QUEUE { get; set; }
        public virtual DbSet<ORDER_CANCEL_REQUESTS> ORDER_CANCEL_REQUESTS { get; set; }
        public virtual DbSet<OUTBOUND_MOVES> OUTBOUND_MOVES { get; set; }
        public virtual DbSet<OUTBOUND_SHIPMENT_DETAILS> OUTBOUND_SHIPMENT_DETAILS { get; set; }
        public virtual DbSet<OUTBOUND_SHIPMENTS> OUTBOUND_SHIPMENTS { get; set; }
        public virtual DbSet<PICKING_RULES> PICKING_RULES { get; set; }
        public virtual DbSet<PICKING_RULES_DETAIL> PICKING_RULES_DETAIL { get; set; }
        public virtual DbSet<POS_Move_Queue> POS_Move_Queue { get; set; }
        public virtual DbSet<PRODUCT_MASTER> PRODUCT_MASTER { get; set; }
        public virtual DbSet<PURCHASE_ORDER_DETAILS> PURCHASE_ORDER_DETAILS { get; set; }
        public virtual DbSet<PURCHASE_ORDERS> PURCHASE_ORDERS { get; set; }
        public virtual DbSet<PURGE_ARCHIVE_RULE> PURGE_ARCHIVE_RULE { get; set; }
        public virtual DbSet<PUTAWAY_RULES> PUTAWAY_RULES { get; set; }
        public virtual DbSet<PUTAWAY_RULES_DETAIL> PUTAWAY_RULES_DETAIL { get; set; }
        public virtual DbSet<QC_CATEGORYS> QC_CATEGORYS { get; set; }
        public virtual DbSet<QC_DEFECTS> QC_DEFECTS { get; set; }
        public virtual DbSet<REPLENISHMENT_RULES> REPLENISHMENT_RULES { get; set; }
        public virtual DbSet<RETURN> RETURNS { get; set; }
        public virtual DbSet<RETURNS_DETAIL> RETURNS_DETAIL { get; set; }
        public virtual DbSet<RETURNS_DISPOSITION> RETURNS_DISPOSITION { get; set; }
        public virtual DbSet<RULES_FINDER> RULES_FINDER { get; set; }
        public virtual DbSet<ScancodeCartonAcceptQueue> ScancodeCartonAcceptQueues { get; set; }
        public virtual DbSet<SITE> SITES { get; set; }
        public virtual DbSet<SUBSTITUTION_RULES> SUBSTITUTION_RULES { get; set; }
        public virtual DbSet<SUPPLIER_ITEM> SUPPLIER_ITEM { get; set; }
        public virtual DbSet<SYSTEM> SYSTEMs { get; set; }
        public virtual DbSet<SYSTEM_CHANGE_REQUESTS> SYSTEM_CHANGE_REQUESTS { get; set; }
        public virtual DbSet<SYSTEMNEXTRID> SYSTEMNEXTRIDs { get; set; }
        public virtual DbSet<TRACELOG> TRACELOGs { get; set; }
        public virtual DbSet<UOM_CONVERSION> UOM_CONVERSION { get; set; }
        public virtual DbSet<VENDOR> VENDORS { get; set; }
        public virtual DbSet<WAIT_LIST> WAIT_LIST { get; set; }
        public virtual DbSet<WORK_QUEUE> WORK_QUEUE { get; set; }
        public virtual DbSet<ABS_PO_Detail> ABS_PO_Detail { get; set; }
        public virtual DbSet<ABS_PO_Header> ABS_PO_Header { get; set; }
        public virtual DbSet<AI_Returns> AI_Returns { get; set; }
        public virtual DbSet<ASN_FILES> ASN_FILES { get; set; }
        public virtual DbSet<ASN_VENDOR_SITE_XREF> ASN_VENDOR_SITE_XREF { get; set; }
        public virtual DbSet<AUDIT_ASN> AUDIT_ASN { get; set; }
        public virtual DbSet<Backup_INV_10002260> Backup_INV_10002260 { get; set; }
        public virtual DbSet<Compare_IBR_Receipts> Compare_IBR_Receipts { get; set; }
        public virtual DbSet<ComparePM2UOM> ComparePM2UOM { get; set; }
        public virtual DbSet<custcity> custcities { get; set; }
        public virtual DbSet<CYCLE_COUNT_REQUESTS> CYCLE_COUNT_REQUESTS { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<EMPLOYEE_ACTIVITY_REPORT> EMPLOYEE_ACTIVITY_REPORT { get; set; }
        public virtual DbSet<FORM> FORMs { get; set; }
        public virtual DbSet<FORM_DETAIL> FORM_DETAIL { get; set; }
        public virtual DbSet<GTIN_BACKUP> GTIN_BACKUP { get; set; }
        public virtual DbSet<IMPORT_DEFS> IMPORT_DEFS { get; set; }
        public virtual DbSet<IMPORT_ENGINE_DEFS> IMPORT_ENGINE_DEFS { get; set; }
        public virtual DbSet<MOVE_QUEUE_ARCHIVE> MOVE_QUEUE_ARCHIVE { get; set; }
        public virtual DbSet<MQREPLEN> MQREPLENs { get; set; }
        public virtual DbSet<New_Inventory> New_Inventory { get; set; }
        public virtual DbSet<PA_Group> PA_Group { get; set; }
        public virtual DbSet<PA_Rule> PA_Rule { get; set; }
        public virtual DbSet<PURGE_ARCHIVE_GROUP> PURGE_ARCHIVE_GROUP { get; set; }
        public virtual DbSet<Returns_Detail__returns> Returns_Detail__returns { get; set; }
        public virtual DbSet<Returns_Disp_returns> Returns_Disp_returns { get; set; }
        public virtual DbSet<RETURNS_DISPOSITION_CSN> RETURNS_DISPOSITION_CSN { get; set; }
        public virtual DbSet<Returns_returns> Returns_returns { get; set; }
        public virtual DbSet<ScancodeCartonAcceptQueueHistory> ScancodeCartonAcceptQueueHistories { get; set; }
        public virtual DbSet<SYSTEMNEXTRID_AUDINV> SYSTEMNEXTRID_AUDINV { get; set; }
        public virtual DbSet<SYSTEMNEXTRID_AUDINVD> SYSTEMNEXTRID_AUDINVD { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<UserAppAccess> UserAppAccesses { get; set; }
    
        public virtual int dt_addtosourcecontrol(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_addtosourcecontrol_u(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol_u", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_adduserobject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject");
        }
    
        public virtual int dt_adduserobject_vcs(string vchProperty)
        {
            var vchPropertyParameter = vchProperty != null ?
                new ObjectParameter("vchProperty", vchProperty) :
                new ObjectParameter("vchProperty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject_vcs", vchPropertyParameter);
        }
    
        public virtual int dt_checkinobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkinobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkoutobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_checkoutobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_displayoaerror(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_displayoaerror_u(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror_u", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_droppropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_droppropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual int dt_dropuserobjectbyid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_dropuserobjectbyid", idParameter);
        }
    
        public virtual int dt_generateansiname(ObjectParameter name)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_generateansiname", name);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop(string property, string value)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop", propertyParameter, valueParameter);
        }
    
        public virtual int dt_getobjwithprop_u(string property, string uvalue)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getobjwithprop_u", propertyParameter, uvalueParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_Result> dt_getpropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_Result>("dt_getpropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual int dt_getpropertiesbyid_u(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_u", idParameter, propertyParameter);
        }
    
        public virtual int dt_getpropertiesbyid_vcs(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_getpropertiesbyid_vcs_u(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs_u", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_isundersourcecontrol(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_isundersourcecontrol_u(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol_u", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_removefromsourcecontrol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_removefromsourcecontrol");
        }
    
        public virtual int dt_setpropertybyid(Nullable<int> id, string property, string value, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid", idParameter, propertyParameter, valueParameter, lvalueParameter);
        }
    
        public virtual int dt_setpropertybyid_u(Nullable<int> id, string property, string uvalue, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid_u", idParameter, propertyParameter, uvalueParameter, lvalueParameter);
        }
    
        public virtual int dt_validateloginparams(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_validateloginparams_u(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams_u", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_vcsenabled()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_vcsenabled");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp006()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp006");
        }
    
        public virtual int dt_whocheckedout(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_whocheckedout_u(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout_u", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int Rules_Fixer_Upper(string productLike)
        {
            var productLikeParameter = productLike != null ?
                new ObjectParameter("ProductLike", productLike) :
                new ObjectParameter("ProductLike", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Rules_Fixer_Upper", productLikeParameter);
        }
    
        public virtual ObjectResult<string> WMS_Bodek_Accept(string carton, string trackingNum, string actWeight, string shipLine, string payFlag, string maniPrinter, string actFreight)
        {
            var cartonParameter = carton != null ?
                new ObjectParameter("Carton", carton) :
                new ObjectParameter("Carton", typeof(string));
    
            var trackingNumParameter = trackingNum != null ?
                new ObjectParameter("TrackingNum", trackingNum) :
                new ObjectParameter("TrackingNum", typeof(string));
    
            var actWeightParameter = actWeight != null ?
                new ObjectParameter("ActWeight", actWeight) :
                new ObjectParameter("ActWeight", typeof(string));
    
            var shipLineParameter = shipLine != null ?
                new ObjectParameter("ShipLine", shipLine) :
                new ObjectParameter("ShipLine", typeof(string));
    
            var payFlagParameter = payFlag != null ?
                new ObjectParameter("PayFlag", payFlag) :
                new ObjectParameter("PayFlag", typeof(string));
    
            var maniPrinterParameter = maniPrinter != null ?
                new ObjectParameter("ManiPrinter", maniPrinter) :
                new ObjectParameter("ManiPrinter", typeof(string));
    
            var actFreightParameter = actFreight != null ?
                new ObjectParameter("ActFreight", actFreight) :
                new ObjectParameter("ActFreight", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("WMS_Bodek_Accept", cartonParameter, trackingNumParameter, actWeightParameter, shipLineParameter, payFlagParameter, maniPrinterParameter, actFreightParameter);
        }
    
        public virtual ObjectResult<string> wms_bodek_accept_cursor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("wms_bodek_accept_cursor");
        }
    
        public virtual int WMS_Bodek_Accept_new(string carton, string trackingNum, string actWeight, string shipLine, string payFlag, string maniPrinter, string actFreight)
        {
            var cartonParameter = carton != null ?
                new ObjectParameter("Carton", carton) :
                new ObjectParameter("Carton", typeof(string));
    
            var trackingNumParameter = trackingNum != null ?
                new ObjectParameter("TrackingNum", trackingNum) :
                new ObjectParameter("TrackingNum", typeof(string));
    
            var actWeightParameter = actWeight != null ?
                new ObjectParameter("ActWeight", actWeight) :
                new ObjectParameter("ActWeight", typeof(string));
    
            var shipLineParameter = shipLine != null ?
                new ObjectParameter("ShipLine", shipLine) :
                new ObjectParameter("ShipLine", typeof(string));
    
            var payFlagParameter = payFlag != null ?
                new ObjectParameter("PayFlag", payFlag) :
                new ObjectParameter("PayFlag", typeof(string));
    
            var maniPrinterParameter = maniPrinter != null ?
                new ObjectParameter("ManiPrinter", maniPrinter) :
                new ObjectParameter("ManiPrinter", typeof(string));
    
            var actFreightParameter = actFreight != null ?
                new ObjectParameter("ActFreight", actFreight) :
                new ObjectParameter("ActFreight", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WMS_Bodek_Accept_new", cartonParameter, trackingNumParameter, actWeightParameter, shipLineParameter, payFlagParameter, maniPrinterParameter, actFreightParameter);
        }
    
        public virtual ObjectResult<string> WMS_Bodek_Accept_Process(string carton, string trackingNum, string actWeight, string shipLine, string payFlag, string maniPrinter, string actFreight)
        {
            var cartonParameter = carton != null ?
                new ObjectParameter("Carton", carton) :
                new ObjectParameter("Carton", typeof(string));
    
            var trackingNumParameter = trackingNum != null ?
                new ObjectParameter("TrackingNum", trackingNum) :
                new ObjectParameter("TrackingNum", typeof(string));
    
            var actWeightParameter = actWeight != null ?
                new ObjectParameter("ActWeight", actWeight) :
                new ObjectParameter("ActWeight", typeof(string));
    
            var shipLineParameter = shipLine != null ?
                new ObjectParameter("ShipLine", shipLine) :
                new ObjectParameter("ShipLine", typeof(string));
    
            var payFlagParameter = payFlag != null ?
                new ObjectParameter("PayFlag", payFlag) :
                new ObjectParameter("PayFlag", typeof(string));
    
            var maniPrinterParameter = maniPrinter != null ?
                new ObjectParameter("ManiPrinter", maniPrinter) :
                new ObjectParameter("ManiPrinter", typeof(string));
    
            var actFreightParameter = actFreight != null ?
                new ObjectParameter("ActFreight", actFreight) :
                new ObjectParameter("ActFreight", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("WMS_Bodek_Accept_Process", cartonParameter, trackingNumParameter, actWeightParameter, shipLineParameter, payFlagParameter, maniPrinterParameter, actFreightParameter);
        }
    
        public virtual ObjectResult<string> WMS_Bodek_Accept3(string carton, string trackingNum, string actWeight, string shipLine, string payFlag, string maniPrinter, string actFreight)
        {
            var cartonParameter = carton != null ?
                new ObjectParameter("Carton", carton) :
                new ObjectParameter("Carton", typeof(string));
    
            var trackingNumParameter = trackingNum != null ?
                new ObjectParameter("TrackingNum", trackingNum) :
                new ObjectParameter("TrackingNum", typeof(string));
    
            var actWeightParameter = actWeight != null ?
                new ObjectParameter("ActWeight", actWeight) :
                new ObjectParameter("ActWeight", typeof(string));
    
            var shipLineParameter = shipLine != null ?
                new ObjectParameter("ShipLine", shipLine) :
                new ObjectParameter("ShipLine", typeof(string));
    
            var payFlagParameter = payFlag != null ?
                new ObjectParameter("PayFlag", payFlag) :
                new ObjectParameter("PayFlag", typeof(string));
    
            var maniPrinterParameter = maniPrinter != null ?
                new ObjectParameter("ManiPrinter", maniPrinter) :
                new ObjectParameter("ManiPrinter", typeof(string));
    
            var actFreightParameter = actFreight != null ?
                new ObjectParameter("ActFreight", actFreight) :
                new ObjectParameter("ActFreight", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("WMS_Bodek_Accept3", cartonParameter, trackingNumParameter, actWeightParameter, shipLineParameter, payFlagParameter, maniPrinterParameter, actFreightParameter);
        }
    
        public virtual int WMS_Bodek_EmpActReport(string reportID, string fromDate, string toDate, string fromEmp, string toEmp)
        {
            var reportIDParameter = reportID != null ?
                new ObjectParameter("ReportID", reportID) :
                new ObjectParameter("ReportID", typeof(string));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            var fromEmpParameter = fromEmp != null ?
                new ObjectParameter("FromEmp", fromEmp) :
                new ObjectParameter("FromEmp", typeof(string));
    
            var toEmpParameter = toEmp != null ?
                new ObjectParameter("ToEmp", toEmp) :
                new ObjectParameter("ToEmp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WMS_Bodek_EmpActReport", reportIDParameter, fromDateParameter, toDateParameter, fromEmpParameter, toEmpParameter);
        }
    
        public virtual int WMS_Bodek_LocActReport(string fromLocation, string toLocation, string fromDate, string toDate)
        {
            var fromLocationParameter = fromLocation != null ?
                new ObjectParameter("FromLocation", fromLocation) :
                new ObjectParameter("FromLocation", typeof(string));
    
            var toLocationParameter = toLocation != null ?
                new ObjectParameter("ToLocation", toLocation) :
                new ObjectParameter("ToLocation", typeof(string));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WMS_Bodek_LocActReport", fromLocationParameter, toLocationParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual int WMS_Bodek_Manifest(string carton)
        {
            var cartonParameter = carton != null ?
                new ObjectParameter("Carton", carton) :
                new ObjectParameter("Carton", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WMS_Bodek_Manifest", cartonParameter);
        }
    
        public virtual int WMS_Bodek_Manifest_20111024(string carton)
        {
            var cartonParameter = carton != null ?
                new ObjectParameter("Carton", carton) :
                new ObjectParameter("Carton", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WMS_Bodek_Manifest_20111024", cartonParameter);
        }
    
        public virtual int WMS_Bodek_Manifest_20111025(string carton)
        {
            var cartonParameter = carton != null ?
                new ObjectParameter("Carton", carton) :
                new ObjectParameter("Carton", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WMS_Bodek_Manifest_20111025", cartonParameter);
        }
    
        public virtual int WMS_Bodek_Manifest_20111027(string carton)
        {
            var cartonParameter = carton != null ?
                new ObjectParameter("Carton", carton) :
                new ObjectParameter("Carton", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WMS_Bodek_Manifest_20111027", cartonParameter);
        }
    
        public virtual int WMS_Bodek_Manifest_20120613(string carton)
        {
            var cartonParameter = carton != null ?
                new ObjectParameter("Carton", carton) :
                new ObjectParameter("Carton", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WMS_Bodek_Manifest_20120613", cartonParameter);
        }
    
        public virtual int WMS_Bodek_Manifest_AgileElite(string carton, ObjectParameter cartonID, ObjectParameter cartonStatus, ObjectParameter cartonInterModalVehicle, ObjectParameter cartonExternOrderKey, ObjectParameter cartonPmtTerm, ObjectParameter cartonC_CustNum, ObjectParameter cartonC_Address1, ObjectParameter cartonC_Address2, ObjectParameter cartonC_Address3, ObjectParameter cartonC_Zip, ObjectParameter cartonC_State, ObjectParameter cartonC_City, ObjectParameter cartonC_Company, ObjectParameter cartonCalcWgt, ObjectParameter cartonCOD_Cost, ObjectParameter cartonTrailerCode, ObjectParameter cartonPhone, ObjectParameter cartonPayFlag, ObjectParameter cartonFREIGHT_BILL_TO_ACCOUNT, ObjectParameter cartonFREIGHT_BILL_TO_NAME, ObjectParameter cartonFREIGHT_BILL_TO_ADDRESS_1, ObjectParameter cartonFREIGHT_BILL_TO_ADDRESS_2, ObjectParameter cartonFREIGHT_BILL_TO_ADDRESS_3, ObjectParameter cartonFREIGHT_BILL_TO_CITY, ObjectParameter cartonFREIGHT_BILL_TO_STATE, ObjectParameter cartonFREIGHT_BILL_TO_ZIP, ObjectParameter cartonCust_PO, ObjectParameter cartonWidth, ObjectParameter cartonLength, ObjectParameter cartonHeight)
        {
            var cartonParameter = carton != null ?
                new ObjectParameter("Carton", carton) :
                new ObjectParameter("Carton", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WMS_Bodek_Manifest_AgileElite", cartonParameter, cartonID, cartonStatus, cartonInterModalVehicle, cartonExternOrderKey, cartonPmtTerm, cartonC_CustNum, cartonC_Address1, cartonC_Address2, cartonC_Address3, cartonC_Zip, cartonC_State, cartonC_City, cartonC_Company, cartonCalcWgt, cartonCOD_Cost, cartonTrailerCode, cartonPhone, cartonPayFlag, cartonFREIGHT_BILL_TO_ACCOUNT, cartonFREIGHT_BILL_TO_NAME, cartonFREIGHT_BILL_TO_ADDRESS_1, cartonFREIGHT_BILL_TO_ADDRESS_2, cartonFREIGHT_BILL_TO_ADDRESS_3, cartonFREIGHT_BILL_TO_CITY, cartonFREIGHT_BILL_TO_STATE, cartonFREIGHT_BILL_TO_ZIP, cartonCust_PO, cartonWidth, cartonLength, cartonHeight);
        }
    
        public virtual int WMS_Bodek_Manifest_Old_20111027(string carton)
        {
            var cartonParameter = carton != null ?
                new ObjectParameter("Carton", carton) :
                new ObjectParameter("Carton", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WMS_Bodek_Manifest_Old_20111027", cartonParameter);
        }
    
        public virtual int WMS_Bodek_Manifest_Old20111024(string carton)
        {
            var cartonParameter = carton != null ?
                new ObjectParameter("Carton", carton) :
                new ObjectParameter("Carton", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WMS_Bodek_Manifest_Old20111024", cartonParameter);
        }
    
        public virtual int WMS_Bodek_NewEmpActReport(string reportID, string fromDate, string toDate, string fromEmp, string toEmp)
        {
            var reportIDParameter = reportID != null ?
                new ObjectParameter("ReportID", reportID) :
                new ObjectParameter("ReportID", typeof(string));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            var fromEmpParameter = fromEmp != null ?
                new ObjectParameter("FromEmp", fromEmp) :
                new ObjectParameter("FromEmp", typeof(string));
    
            var toEmpParameter = toEmp != null ?
                new ObjectParameter("ToEmp", toEmp) :
                new ObjectParameter("ToEmp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WMS_Bodek_NewEmpActReport", reportIDParameter, fromDateParameter, toDateParameter, fromEmpParameter, toEmpParameter);
        }
    
        public virtual int WMS_Bodek_Reset()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WMS_Bodek_Reset");
        }
    
        public virtual int WMS_ClearTableLocks(string tablename)
        {
            var tablenameParameter = tablename != null ?
                new ObjectParameter("tablename", tablename) :
                new ObjectParameter("tablename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WMS_ClearTableLocks", tablenameParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> WMS_Daily_Shipping_Numbers(Nullable<System.DateTime> queryDate)
        {
            var queryDateParameter = queryDate.HasValue ?
                new ObjectParameter("QueryDate", queryDate) :
                new ObjectParameter("QueryDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("WMS_Daily_Shipping_Numbers", queryDateParameter);
        }
    
        public virtual int WMS_Maint_Build_Size_Table()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WMS_Maint_Build_Size_Table");
        }
    
        public virtual int WMS_Maint_Purge_Tables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WMS_Maint_Purge_Tables");
        }
    
        public virtual int WMS_Reindex_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WMS_Reindex_All");
        }
    }
}
