//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_Rule
    {
        public string GROUP_NAME { get; set; }
        public short ARCHIVE_DAYS { get; set; }
        public short PURGE_DAYS { get; set; }
        public Nullable<System.DateTime> LAST_ARCHIVED { get; set; }
        public Nullable<System.DateTime> LAST_PURGED { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
        public Nullable<short> purge_only { get; set; }
    }
}
