//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PICKING_RULES
    {
        public string RULE_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> MIN_DAYS_TO_EXPIRE { get; set; }
        public Nullable<int> MIN_DAYS_OLD { get; set; }
        public string DEFAULT_ALGORITHIM { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
    }
}
