//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_Move_Queue
    {
        public decimal C_rid_ { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Status { get; set; }
        public string FromLocation { get; set; }
        public string ToLocation { get; set; }
        public string User_ID_Intransit { get; set; }
        public string ShipmentID { get; set; }
        public string OrderNumber { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string LastUser { get; set; }
    }
}
