//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASN_LAYOUT
    {
        public string SHIPMENT_ID { get; set; }
        public string SHORT_DESCRIPTION { get; set; }
        public string LAYOUT_CODE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
    }
}
