//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Manifest
    {
        public string CaseID { get; set; }
        public System.DateTime Transaction_Time { get; set; }
        public string TranType { get; set; }
        public string SubType { get; set; }
        public string StationID { get; set; }
        public string Message { get; set; }
        public string Status { get; set; }
    }
}
