//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_OUTBOUND_DETAIL
    {
        public int C_RID_ { get; set; }
        public int AUDIT_OUTBOUND_RID { get; set; }
        public string SHIPMENT_ID { get; set; }
        public string ORDER_NUMBER { get; set; }
        public string ORDER_NUMBER_OLD { get; set; }
        public Nullable<int> ORDER_LINE { get; set; }
        public Nullable<int> ORDER_LINE_OLD { get; set; }
        public string PRODUCT_ID { get; set; }
        public string PRODUCT_ID_OLD { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE_OLD { get; set; }
        public Nullable<System.DateTime> PICK_ASSIGNED_TIME { get; set; }
        public Nullable<System.DateTime> PICK_START_TIME { get; set; }
        public Nullable<System.DateTime> PICK_COMPLETE_TIME { get; set; }
        public string PICKER { get; set; }
        public Nullable<float> UNITS_ORDERED { get; set; }
        public Nullable<float> UNITS_STAGED { get; set; }
        public Nullable<float> UNITS_VERIFIED { get; set; }
        public Nullable<float> UNITS_SHIPPED { get; set; }
        public string ADJUSTMENT_CODE { get; set; }
        public string ADJUSTMENT_CODE_OLD { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
        public string STATUS { get; set; }
        public string STATUS_OLD { get; set; }
        public Nullable<float> UNITS_ORDERED_OLD { get; set; }
        public string TRANTYPE { get; set; }
        public string SUBTYPE { get; set; }
        public Nullable<System.DateTime> TRANSACTION_TIME { get; set; }
        public string QC_AUDITOR { get; set; }
    }
}
