//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRIER
    {
        public string CARRIER_ID { get; set; }
        public string POOL_POINT { get; set; }
        public string NAME { get; set; }
        public string ADDRESS_1 { get; set; }
        public string ADDRESS_2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_PHONE { get; set; }
        public string COMMENTS_1 { get; set; }
        public string COMMENTS_2 { get; set; }
        public string COMMENTS_3 { get; set; }
        public string COMMENTS_4 { get; set; }
        public string ACCOUNT_NUMBER { get; set; }
        public string ICC_NUMBER { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
        public string COMPANY_NAME { get; set; }
        public string TYPE { get; set; }
        public string SHIP_MODE_DEFAULT { get; set; }
    }
}
