//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case_Count
    {
        public string Order_Number { get; set; }
        public string Order_Line { get; set; }
        public string Product_ID { get; set; }
        public string Skid_Number { get; set; }
        public Nullable<System.DateTime> C_Last_updated { get; set; }
        public string C_Last_User { get; set; }
    }
}
