//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIPPERSHIP
    {
        public string Caseid { get; set; }
        public string Status { get; set; }
        public string InterModalVehicle { get; set; }
        public string ExternOrderKey { get; set; }
        public string OrderKey { get; set; }
        public string CaseType { get; set; }
        public string PmtTerm { get; set; }
        public string BR_BookID { get; set; }
        public string C_CustNum { get; set; }
        public string C_Address1 { get; set; }
        public string C_Address2 { get; set; }
        public string C_Zip { get; set; }
        public string C_State { get; set; }
        public string C_City { get; set; }
        public string C_Company { get; set; }
        public Nullable<decimal> CalcWgt { get; set; }
        public Nullable<decimal> COD_Cost { get; set; }
        public string TrailerCode { get; set; }
        public string Phone { get; set; }
        public Nullable<decimal> Freight_Charge { get; set; }
        public string TrackingNum { get; set; }
        public string ActWeight { get; set; }
        public string ShipLine { get; set; }
        public string PayFlag { get; set; }
        public Nullable<System.DateTime> EXPORTTIME_SYS1 { get; set; }
        public string EXPORTFILENAME_SYS1 { get; set; }
        public Nullable<System.DateTime> EXPORTTIME_SYS2 { get; set; }
        public string EXPORTFILENAME_SYS2 { get; set; }
        public Nullable<decimal> DEPOSIT_AMOUNT { get; set; }
        public string FREIGHT_BILL_TO_ACCOUNT { get; set; }
        public string FREIGHT_BILL_TO_NAME { get; set; }
        public string FREIGHT_BILL_TO_ADDRESS_1 { get; set; }
        public string FREIGHT_BILL_TO_ADDRESS_2 { get; set; }
        public string FREIGHT_BILL_TO_ADDRESS_3 { get; set; }
        public string FREIGHT_BILL_TO_CITY { get; set; }
        public string FREIGHT_BILL_TO_STATE { get; set; }
        public string FREIGHT_BILL_TO_ZIP { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
        public string Cust_PO { get; set; }
        public Nullable<decimal> ActFreight { get; set; }
        public string EXPORTFDM4BATCH_SYS1 { get; set; }
        public string C_Address3 { get; set; }
    }
}
