//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSOLIDATION_RULES
    {
        public string RULE_ID { get; set; }
        public string QC_CATEGORY { get; set; }
        public bool MIX_LOTS { get; set; }
        public bool MIX_LINES { get; set; }
        public bool MIX_SHIFTS { get; set; }
        public bool MIX_PURCHASE_ORDERS { get; set; }
        public bool MIX_QUALITY_CATEGORIES { get; set; }
        public bool MIX_PRODUCT { get; set; }
        public Nullable<short> CONSOLIDATION_DAY_WINDOW { get; set; }
        public Nullable<int> MAX_DAYS_SINCE_ARRIVAL { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
    }
}
