//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_GROUPS
    {
        public string EMAIL_GROUP { get; set; }
        public string FRIENDLY_NAME { get; set; }
        public string STATUS { get; set; }
        public string LAST_MODULE { get; set; }
        public string LAST_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
    }
}
