//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class INBOUND_SERIAL
    {
        public string SHIPMENT_ID { get; set; }
        public string ORDER_NUMBER { get; set; }
        public string PRODUCT_ID { get; set; }
        public int CSN_RID { get; set; }
        public string SERIAL { get; set; }
        public string STATUS { get; set; }
        public string MFG_DATA1 { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
    }
}
