//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_SERIAL
    {
        public int C_RID_ { get; set; }
        public Nullable<int> INV_RID { get; set; }
        public string CASELABEL { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public Nullable<System.DateTime> DATA1DATE { get; set; }
        public Nullable<float> DATA1NUM { get; set; }
        public string DATA2STR { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
    }
}
