//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WMSEntities : DbContext
    {
        public WMSEntities()
            : base("name=WMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Audit_Manifest> Audit_Manifest { get; set; }
        public virtual DbSet<AUDIT_OUTBOUND> AUDIT_OUTBOUND { get; set; }
        public virtual DbSet<AUDIT_OUTBOUND_DETAIL> AUDIT_OUTBOUND_DETAIL { get; set; }
        public virtual DbSet<Cashier_Notes> Cashier_Notes { get; set; }
        public virtual DbSet<Cashier_Transactions> Cashier_Transactions { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<ERRORS_RUNTIME> ERRORS_RUNTIME { get; set; }
        public virtual DbSet<FREIGHT_LANES> FREIGHT_LANES { get; set; }
        public virtual DbSet<GTIN_XREF> GTIN_XREF { get; set; }
        public virtual DbSet<HOST_ORDER_DETAIL> HOST_ORDER_DETAIL { get; set; }
        public virtual DbSet<HOST_ORDERS> HOST_ORDERS { get; set; }
        public virtual DbSet<INVENTORY_ALLOCATION> INVENTORY_ALLOCATION { get; set; }
        public virtual DbSet<MOVE_QUEUE> MOVE_QUEUE { get; set; }
        public virtual DbSet<OUTBOUND_SHIPMENT_DETAILS> OUTBOUND_SHIPMENT_DETAILS { get; set; }
        public virtual DbSet<OUTBOUND_SHIPMENTS> OUTBOUND_SHIPMENTS { get; set; }
        public virtual DbSet<POS_Move_Queue> POS_Move_Queue { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SYSTEM> SYSTEMs { get; set; }
        public virtual DbSet<SYSTEMNEXTRID> SYSTEMNEXTRIDs { get; set; }
        public virtual DbSet<ABS_PO_Detail> ABS_PO_Detail { get; set; }
        public virtual DbSet<ABS_PO_Header> ABS_PO_Header { get; set; }
        public virtual DbSet<ADJUSTMENT_CODES> ADJUSTMENT_CODES { get; set; }
        public virtual DbSet<ADJUSTMENT_CODES_old> ADJUSTMENT_CODES_old { get; set; }
        public virtual DbSet<AFX_BROWSER_APPS> AFX_BROWSER_APPS { get; set; }
        public virtual DbSet<AFX_BROWSER_LINKS> AFX_BROWSER_LINKS { get; set; }
        public virtual DbSet<AFX_BROWSER_MENU> AFX_BROWSER_MENU { get; set; }
        public virtual DbSet<AFX_CONSOLE_APPS> AFX_CONSOLE_APPS { get; set; }
        public virtual DbSet<AFX_CONSOLE_LINKS> AFX_CONSOLE_LINKS { get; set; }
        public virtual DbSet<AFX_CONSOLE_MENU> AFX_CONSOLE_MENU { get; set; }
        public virtual DbSet<AFX_GROUPS> AFX_GROUPS { get; set; }
        public virtual DbSet<AFX_PREFERENCES> AFX_PREFERENCES { get; set; }
        public virtual DbSet<AFX_RIGHTS> AFX_RIGHTS { get; set; }
        public virtual DbSet<AFX_SYSINFO> AFX_SYSINFO { get; set; }
        public virtual DbSet<AFX_SYSTABLEMAP> AFX_SYSTABLEMAP { get; set; }
        public virtual DbSet<AFX_SYSTEMS> AFX_SYSTEMS { get; set; }
        public virtual DbSet<AFX_TABLES> AFX_TABLES { get; set; }
        public virtual DbSet<AFX_USERS> AFX_USERS { get; set; }
        public virtual DbSet<ASN_LAYOUT> ASN_LAYOUT { get; set; }
        public virtual DbSet<ASN_VENDOR_SITE_XREF> ASN_VENDOR_SITE_XREF { get; set; }
        public virtual DbSet<AUDIT_ASN> AUDIT_ASN { get; set; }
        public virtual DbSet<AUDIT_INBOUND> AUDIT_INBOUND { get; set; }
        public virtual DbSet<AUDIT_INBOUND_DETAIL> AUDIT_INBOUND_DETAIL { get; set; }
        public virtual DbSet<AUDIT_INVENTORY> AUDIT_INVENTORY { get; set; }
        public virtual DbSet<AUDIT_INVENTORY_DETAIL> AUDIT_INVENTORY_DETAIL { get; set; }
        public virtual DbSet<BOL_CLASS> BOL_CLASS { get; set; }
        public virtual DbSet<CARRIER> CARRIERS { get; set; }
        public virtual DbSet<CARTON_MASTER> CARTON_MASTER { get; set; }
        public virtual DbSet<Case_Count> Case_Count { get; set; }
        public virtual DbSet<CLIPPERSHIP> CLIPPERSHIPs { get; set; }
        public virtual DbSet<CONSOLIDATION_RULES> CONSOLIDATION_RULES { get; set; }
        public virtual DbSet<custcity> custcities { get; set; }
        public virtual DbSet<custcity1> custcity1 { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERS { get; set; }
        public virtual DbSet<CYCLE_COUNT_RESULTS> CYCLE_COUNT_RESULTS { get; set; }
        public virtual DbSet<DOCK_ACTIVITY> DOCK_ACTIVITY { get; set; }
        public virtual DbSet<DOOR> DOORS { get; set; }
        public virtual DbSet<EMAIL_ALIAS> EMAIL_ALIAS { get; set; }
        public virtual DbSet<EMAIL_GROUPS> EMAIL_GROUPS { get; set; }
        public virtual DbSet<EMAIL_QUEUE> EMAIL_QUEUE { get; set; }
        public virtual DbSet<EMPLOYEE_ACTIVITY_REPORT> EMPLOYEE_ACTIVITY_REPORT { get; set; }
        public virtual DbSet<ERRORS_USAGE> ERRORS_USAGE { get; set; }
        public virtual DbSet<HOST_INVENTORY_EFFECT> HOST_INVENTORY_EFFECT { get; set; }
        public virtual DbSet<HOST_INVENTORY_STATE> HOST_INVENTORY_STATE { get; set; }
        public virtual DbSet<HOST_PRODMAST> HOST_PRODMAST { get; set; }
        public virtual DbSet<IMPORT_ENGINE_DEFS> IMPORT_ENGINE_DEFS { get; set; }
        public virtual DbSet<INBOUND_CSN> INBOUND_CSN { get; set; }
        public virtual DbSet<INBOUND_MOVES> INBOUND_MOVES { get; set; }
        public virtual DbSet<INBOUND_SERIAL> INBOUND_SERIAL { get; set; }
        public virtual DbSet<INBOUND_SHIPMENT_DETAIL> INBOUND_SHIPMENT_DETAIL { get; set; }
        public virtual DbSet<INBOUND_SHIPMENTS> INBOUND_SHIPMENTS { get; set; }
        public virtual DbSet<INVENTORY> INVENTORies { get; set; }
        public virtual DbSet<INVENTORY_SERIAL> INVENTORY_SERIAL { get; set; }
        public virtual DbSet<LOCATION_CAPACITY> LOCATION_CAPACITY { get; set; }
        public virtual DbSet<LOCATION> LOCATIONS { get; set; }
        public virtual DbSet<LOOKUP_VALUES> LOOKUP_VALUES { get; set; }
        public virtual DbSet<LOOKUP_VALUES_old> LOOKUP_VALUES_old { get; set; }
        public virtual DbSet<MOVE_QUEUE_ARCHIVE> MOVE_QUEUE_ARCHIVE { get; set; }
        public virtual DbSet<PICKING_RULES> PICKING_RULES { get; set; }
        public virtual DbSet<PICKING_RULES_DETAIL> PICKING_RULES_DETAIL { get; set; }
        public virtual DbSet<PRODUCT_MASTER> PRODUCT_MASTER { get; set; }
        public virtual DbSet<PRODUCT_MASTER_20091106BAK> PRODUCT_MASTER_20091106BAK { get; set; }
        public virtual DbSet<PURCHASE_ORDER_DETAILS> PURCHASE_ORDER_DETAILS { get; set; }
        public virtual DbSet<PURCHASE_ORDERS> PURCHASE_ORDERS { get; set; }
        public virtual DbSet<PURGE_ARCHIVE_GROUP> PURGE_ARCHIVE_GROUP { get; set; }
        public virtual DbSet<PURGE_ARCHIVE_RULE> PURGE_ARCHIVE_RULE { get; set; }
        public virtual DbSet<PUTAWAY_RULES> PUTAWAY_RULES { get; set; }
        public virtual DbSet<PUTAWAY_RULES_DETAIL> PUTAWAY_RULES_DETAIL { get; set; }
        public virtual DbSet<QC_CATEGORYS> QC_CATEGORYS { get; set; }
        public virtual DbSet<QC_DEFECTS> QC_DEFECTS { get; set; }
        public virtual DbSet<REPLENISHMENT_RULES> REPLENISHMENT_RULES { get; set; }
        public virtual DbSet<RETURN> RETURNS { get; set; }
        public virtual DbSet<RETURNS_DETAIL> RETURNS_DETAIL { get; set; }
        public virtual DbSet<RETURNS_DISPOSITION> RETURNS_DISPOSITION { get; set; }
        public virtual DbSet<RETURNS_DISPOSITION_CSN> RETURNS_DISPOSITION_CSN { get; set; }
        public virtual DbSet<RULES_FINDER> RULES_FINDER { get; set; }
        public virtual DbSet<SITE> SITES { get; set; }
        public virtual DbSet<SUBSTITUTION_RULES> SUBSTITUTION_RULES { get; set; }
        public virtual DbSet<SUPPLIER_ITEM> SUPPLIER_ITEM { get; set; }
        public virtual DbSet<SYSTEMNEXTRID_AUDINV> SYSTEMNEXTRID_AUDINV { get; set; }
        public virtual DbSet<SYSTEMNEXTRID_AUDINVD> SYSTEMNEXTRID_AUDINVD { get; set; }
        public virtual DbSet<Temp_asn> Temp_asn { get; set; }
        public virtual DbSet<TRACELOG> TRACELOGs { get; set; }
        public virtual DbSet<unalloc_inv> unalloc_inv { get; set; }
        public virtual DbSet<UOM_CONVERSION> UOM_CONVERSION { get; set; }
        public virtual DbSet<VENDOR> VENDORS { get; set; }
        public virtual DbSet<VENDORS_old> VENDORS_old { get; set; }
        public virtual DbSet<WAIT_LIST> WAIT_LIST { get; set; }
        public virtual DbSet<WORK_QUEUE> WORK_QUEUE { get; set; }
    }
}
