//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETURNS_DISPOSITION_CSN
    {
        public int RETURNS_DISPOSITION_RID { get; set; }
        public float QUANTITY { get; set; }
        public string RETURN_ID { get; set; }
        public string PRODUCT_ID { get; set; }
        public string C_LAST_MODULE_ { get; set; }
    }
}
