//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAIT_LIST
    {
        public int C_RID_ { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> SEQUENCE { get; set; }
        public Nullable<System.DateTime> APPOINTMENT_TIME { get; set; }
        public string CARRIER_ID { get; set; }
        public Nullable<System.DateTime> CHECK_IN_TIME { get; set; }
        public string SHIPMENT_ID { get; set; }
        public string SHIP_TO { get; set; }
        public Nullable<int> DURATION { get; set; }
        public string DOOR_ID { get; set; }
        public string STATUS { get; set; }
        public string LABOR { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
    }
}
