//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORK_QUEUE
    {
        public int C_RID_ { get; set; }
        public string STATUS { get; set; }
        public string TYPE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string FROM_ZONE { get; set; }
        public string FROM_LOCATION { get; set; }
        public string TO_ZONE { get; set; }
        public string TO_LOCATION { get; set; }
        public Nullable<int> INV_RID { get; set; }
        public Nullable<System.DateTime> DATA1DATE { get; set; }
        public Nullable<float> DATA1NUM { get; set; }
        public string DATA1STR { get; set; }
        public Nullable<System.DateTime> DATA2DATE { get; set; }
        public Nullable<float> DATA2NUM { get; set; }
        public string DATA2STR { get; set; }
        public Nullable<System.DateTime> DATA3DATE { get; set; }
        public Nullable<float> DATA3NUM { get; set; }
        public string DATA3STR { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATED_ { get; set; }
        public string C_LAST_USER_ { get; set; }
        public string C_LAST_MODULE_ { get; set; }
    }
}
